name: 建立 Linux 版本

on:
  push:
    tags:
      - 'l*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: 建立 Linux 可執行檔
    runs-on: ubuntu-latest
    steps:
      - name: 取得原始碼
        uses: actions/checkout@v4

      - name: 設定 Node.js (v20)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 安裝 Rust 工具鏈
        uses: dtolnay/rust-toolchain@stable

      - name: 安裝 Linux 相依套件 (Ubuntu only)
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf xdg-utils

      - name: 快取 Rust 相依套件
        uses: Swatinem/rust-cache@v2

      - name: 輸出 Node.js版本 / Rust版本
        run: |
          node --version
          rustc --version

      - name: 安裝前端相依套件 (package-lock.json)
        run: npm ci

      - name: 建置應用程式
        run: npm run tauri build
      
      - name: 列出產物目錄 (Ubuntu)
        run: ls src-tauri/target/release/

      - name: 取得 AppImage 檔名
        id: get_appimage_name
        run: echo "APPIMAGE=src-tauri/target/release/tauri_ffmpeg_gui" >> $GITHUB_ENV

      - name: 上傳產物
        uses: actions/upload-artifact@v4
        with:
          name: FFmpegGUI-linux-x86_64.AppImage
          path: ${{ env.APPIMAGE }}
      
      - name: 建立 Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "Linux 版本 ${{ github.ref_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 上傳執行檔到 Release (x86_64)
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.APPIMAGE }}
          asset_name: FFmpegGUI-linux-x86_64.AppImage
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
